# Generated by Django 5.0 on 2024-01-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
