# Generated by Django 5.0.1 on 2024-02-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuinfo',
            name='menu_title',
        ),
    ]
