# Generated by Django 5.0.1 on 2024-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinfo',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
