# Generated by Django 4.1.13 on 2024-01-17 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_menu_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photo_post_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveIndex(
            model_name='menu',
            name='blog_menu_priorit_86fc71_idx',
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['priority'], name='blog_menu_priorit_353507_idx'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='images',
            field=models.ManyToManyField(related_name='photo_posts', to='blog.image'),
        ),
        migrations.AddIndex(
            model_name='photopost',
            index=models.Index(fields=['-publish'], name='blog_photop_publish_b50e72_idx'),
        ),
    ]
