# Generated by Django 4.1.13 on 2024-02-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_menuinfo_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinfo',
            name='menu_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.menu'),
        ),
    ]
