# Generated by Django 5.0.1 on 2024-02-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_menuinfo_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuinfo',
            options={'ordering': ['priority']},
        ),
        migrations.AddIndex(
            model_name='menuinfo',
            index=models.Index(fields=['priority'], name='blog_menuin_priorit_7329a7_idx'),
        ),
    ]
