# Generated by Django 4.1.13 on 2024-02-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_menuinfo_menu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='content_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
