# Generated by Django 5.0.1 on 2024-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_fileupload_alter_photopost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='pdf_documents/'),
        ),
    ]
