# Generated by Django 5.0.1 on 2024-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_menuinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuinfo',
            options={'ordering': ['menu_title']},
        ),
        migrations.AddField(
            model_name='menuinfo',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='menuinfo',
            index=models.Index(fields=['priority'], name='blog_menuin_priorit_7329a7_idx'),
        ),
    ]
