# Generated by Django 5.0.1 on 2024-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_menuinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuinfo',
            options={'ordering': ['menu_title']},
        ),
        migrations.AddIndex(
            model_name='menuinfo',
            index=models.Index(fields=['menu_title'], name='blog_menuin_menu_ti_657cd1_idx'),
        ),
    ]
