# Generated by Django 5.0.1 on 2024-02-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_menuinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='content_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
